[package]
name = "encoder"
version = "0.1.0"
edition = "2024"

[dependencies]
gaussian_parser = {path = "../../crates/gaussian_parser" }
gaussian_sorter = {path = "../../crates/gaussian_sorter"}
rans_coding = {path = "../../crates/rans_coding"}
deflate_coder = {path = "../../crates/deflate_coder"}
decoder = {path = "../decoder"}
rand = "0.10.0-rc.0"
